<a href="https://colab.research.google.com/github/Geto01/ProgramacionAplicada/blob/main/Corte2/Numpy/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
sample_list = [1,2,3]
np.array(sample_list)

array([1, 2, 3])

In [ ]:
my_vector = np.array(['this','is','a','vector'])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
np.eye(50)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
sample_size = 10
np.random.rand(sample_size)

array([0.82134859, 0.36583035, 0.93136275, 0.45786037, 0.21407006,
       0.7649779 , 0.58326889, 0.44386451, 0.55464731, 0.28236087])

In [ ]:
sample_size = 10
np.random.randn(sample_size)

array([ 0.85397958, -1.34060184,  2.32281711,  0.25468504, -1.97767667,
        1.8492283 ,  0.43495912,  0.36971453,  0.39974529,  1.52325637])

In [ ]:
low=1
high=10
sample_size = 10
np.random.randint(low, high, sample_size)

array([6, 2, 7, 7, 5, 8, 2, 8, 6, 6])

In [ ]:
arr = np.array([0,1,2,3,4,5])

arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr = np.array([0,1,2,3,4,5])

arr.shape

arr = arr.reshape(2,3)

arr.shape

(2, 3)

In [ ]:
arr.reshape(2,3).shape

(2, 3)

In [ ]:
simple_array = [1, 2, 3, 4]
simple_array_np = np.array(simple_array)
print('max:',simple_array_np.max(),
'pos:',simple_array_np.argmax(),
'min:',simple_array_np.min(),
'pos:',simple_array_np.argmin())

max: 4 pos: 3 min: 1 pos: 0


In [ ]:
arr = np.arange(4)

arr

array([0, 1, 2, 3])

In [ ]:
2 + arr

array([2, 3, 4, 5])

In [ ]:
arr + arr

array([0, 2, 4, 6])

In [ ]:
arr - 10

array([-10,  -9,  -8,  -7])

In [ ]:
arr - arr

array([0, 0, 0, 0])

In [ ]:
arr * 6

array([ 0,  6, 12, 18])

In [ ]:
arr * arr

array([0, 1, 4, 9])

In [ ]:
arr/2

array([0. , 0.5, 1. , 1.5])

In [ ]:
arr/arr

<ipython-input-70-1862401812>:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [ ]:
np.sin(arr)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [ ]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 ])

In [ ]:
np.log(arr)

<ipython-input-74-3120950136>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229])

In [ ]:
arr = np.random.rand(5)
print(arr)

[0.74281976 0.6135899  0.95771486 0.75281487 0.9764964 ]


In [ ]:
arr= np.round(arr, 2)
print(arr)

[0.74 0.61 0.96 0.75 0.98]


In [ ]:
print(arr[0])
print(arr[:])
print(arr[1:])
print(arr[1:4])

0.0
[0.  0.  0.5 0.5 0.5]
[0.  0.5 0.5 0.5]
[0.  0.5 0.5]


In [ ]:
arr[:] = 0
print(arr)
arr[2:5] = 0.5
print(arr)

[0. 0. 0. 0. 0.]
[0.  0.  0.5 0.5 0.5]


In [ ]:
new_array = np.array([6, 7, 8, 9])
second_new_array = new_array[0:2]
print(second_new_array)
second_new_array[1] = 4
print(second_new_array)
new_array

[6 7]
[6 4]


array([6, 4, 8, 9])

In [ ]:
array_to_copy = np.array([1, 2, 3])
copied_array = array_to_copy.copy()
print('original',array_to_copy)
print('copia',copied_array)
copied_array[0] = 9
print('copia modi',copied_array)
array_to_copy

original [1 2 3]
copia [1 2 3]
copia modi [9 2 3]


array([1, 2, 3])

In [ ]:
mat = np.array([[5, 10, 15],[20, 25, 30],[35, 40, 45]])
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
print(mat[0])
print(mat[0][-1])

[ 5 10 15]
15


In [ ]:
mat[1:][:2]

array([[20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr = np.array([0.69, 0.94, 0.66, 0.73, 0.83])
arr > 0.7

array([False,  True, False,  True,  True])

In [ ]:
arr[arr > 0.7]

array([0.94, 0.73, 0.83])